# -*- coding: utf-8 -*-
"""ml_failure.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AzYdE1I1jZQNPP7ZO-MlewdN87dJXaJl
"""

import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

def generate_synthetic_data(n_samples=200):
    # Random data: strain, stress, material_type, label (0=safe, 1=fail)
    np.random.seed(42)
    strain = np.random.uniform(0, 0.01, n_samples)
    stress = np.random.uniform(0, 400, n_samples)
    material = np.random.randint(0, 2, n_samples)
    # Rule: fail if stress > 250 & strain > 0.005
    label = ((stress > 250) & (strain > 0.005)).astype(int)
    X = np.vstack([strain, stress, material]).T
    return X, label

def train_failure_predictor(X, y):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
    clf = RandomForestClassifier(n_estimators=50, random_state=1)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print("ML Failure Prediction Report:")
    print(classification_report(y_test, y_pred))
    return clf

def predict_failure(clf, new_data):
    return clf.predict(new_data)